version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: postgres
      POSTGRES_DB: boilerplate
    # volumes:
    #   - ./pgdata/var/lib/postgresql/data
    # ports:
    #   - '6543:5432'
  redis:
    image: redis
  api:
    build: .
    depends_on:
      - db
      - redis
    links:
      - redis
      - db
    ports:
      - '8888:8888'
    environment:
      - REDIS_POST=6379
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_PORT=5432
